<a href="https://colab.research.google.com/github/drshahizan/python-tutorial/blob/main/exercise/IzzatHaqeemi/Exercise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing using pandas
This tutorial explains how to preprocess data using the pandas library. Preprocessing is the process of doing a pre-analysis of data, in order to transform them into a standard and normalized format.
Preprocessing involves the following aspects:
* missing values
* data standardization
* data normalization
* data binning

In this tutorial we will use the dataset related to Hepatitis, which can be downloaded from [this link](https://https://raw.githubusercontent.com/drshahizan/dataset/main/hepatitis.csv).

In this tutorial we deal only with missing values.

## Import data
Firstly, import data using the pandas library and convert them into a dataframe. Through the `head(10)` method we print only the first 10 rows of the dataset

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/drshahizan/dataset/main/eda/hepatitis.csv')
df.head(20)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.0,42.0,3.5,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.0,32.0,4.0,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.7,46.0,52.0,4.0,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,200.0,4.0,NaN,False,live
5,34,female,True,False,False,False,False,True,False,False,False,False,False,0.9,95.0,28.0,4.0,75.0,False,live
6,51,female,False,False,True,False,True,True,False,True,True,False,False,NaN,NaN,NaN,NaN,NaN,False,die
7,23,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,NaN,NaN,NaN,False,live
8,39,female,True,False,True,False,False,True,True,False,False,False,False,0.7,NaN,48.0,4.4,NaN,False,live
9,30,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,120.0,3.9,NaN,False,live
10,39,female,False,True,False,False,False,False,True,False,False,False,False,1.3,78.0,30.0,4.4,85.0,False,live
11,32,female,True,True,True,False,False,True,True,False,True,False,False,1.0,59.0,249.0,3.7,54.0,False,live
12,41,female,True,True,True,False,False,True,True,False,False,False,False,0.9,81.0,60.0,3.9,52.0,False,live
13,30,female,True,False,True,False,False,True,True,False,False,False,False,2.2,57.0,144.0,4.9,78.0,False,live
14,47,female,False,True,False,False,False,True,False,False,False,False,False,NaN,NaN,60.0,NaN,NaN,False,live
15,38,female,False,False,True,True,True,True,False,False,False,True,False,2.0,72.0,89.0,2.9,46.0,False,live
16,66,female,True,False,True,False,False,True,False,False,False,False,False,1.2,102.0,53.0,4.3,NaN,False,live
17,40,female,False,False,True,False,False,True,True,False,False,False,False,0.6,62.0,166.0,4.0,63.0,False,live
18,38,female,True,False,False,False,False,True,False,False,False,False,False,0.7,53.0,42.0,4.1,85.0,True,live
19,38,female,False,True,False,False,False,False,True,False,False,False,False,0.7,70.0,28.0,4.2,62.0,False,live

## Identify missing values
We note that the dataset presents some problems. For example, the column email is not available for all the rows. In some cases it presents the `NaN` value, which means that the value is missing.

In order to check whether our dataset contains missing values, we can use the function `isna()`, which returns if an cell of the dataset if `NaN` or not. Then we can count how many missing values there are for each column.

In [ ]:
df.isna().sum()

age                 0
sex                 0
steroid             1
antivirals          0
fatigue             1
malaise             1
anorexia            1
liver_big          10
liver_firm         11
spleen_palpable     5
spiders             5
ascites             5
varices             5
bilirubin           6
alk_phosphate      29
sgot                4
albumin            16
protime            67
histology           0
class               0
dtype: int64

Now we can count the percentage of missing values for each column, simply by dividing the previous result by the length of the dataset (`len(df)`) and multiplying per 100.

In [ ]:
df.isna().sum()/len(df)*100

age                 0.000000
sex                 0.000000
steroid             0.645161
antivirals          0.000000
fatigue             0.645161
malaise             0.645161
anorexia            0.645161
liver_big           6.451613
liver_firm          7.096774
spleen_palpable     3.225806
spiders             3.225806
ascites             3.225806
varices             3.225806
bilirubin           3.870968
alk_phosphate      18.709677
sgot                2.580645
albumin            10.322581
protime            43.225806
histology           0.000000
class               0.000000
dtype: float64

When dealing with missing values, different alternatives can be applied:
* check the source, for example by contacting the data source to correct the missing values
* drop missing values
* replace the missing value with a value
* leave the missing value as it is.

## Drop missing values
Dropping missing values can be one of the following alternatives:
* remove rows having missing values
* remove the whole column containing missing values
We can use the `dropna()` by specifying the `axis` to be considered. If we set `axis = 0` we drop the entire row, if we set `axis = 1` we drop the whole column. If we apply the function `df.dropna(axis=0)` 80 rows of the dataset remain. If we apply the function `df.dropna(axis=1)`, only the columns age, sex, antivirals, histology and class remain. However, removed values are not applied to the original dataframe, but only to the result. We can use the argument `inplace=True` in order to store changes in the original dataframe `df` (`df.dropna(axis=1,inplace=True)`).

In [ ]:
df.dropna(axis=1)

     age     sex  antivirals  histology class
0     30    male       False      False  live
1     50  female       False      False  live
2     78  female       False      False  live
3     31  female        True      False  live
4     34  female       False      False  live
..   ...     ...         ...        ...   ...
150   46  female       False       True   die
151   44  female       False       True  live
152   61  female       False       True  live
153   53    male       False       True  live
154   43  female       False       True   die

[155 rows x 5 columns]

As an alternative, we can specify only the column on which the dropping operation must be applied. In the following example, only missing rows related to the column `liver_big` are considered. This can be achieved through the `subset` parameter, which permits to specify the subset of columns where to apply the dropping operation.

In [ ]:
df.dropna(subset=['liver_big'],axis=0,inplace=True)

Now we can check whether there are still missing values for the column `indirizzo`.

df.isna().sum()/len(df)*100

Another alternative involves the dropping of columns where a certain percentage of not-null values is available. This can be achieved through the `thresh` parameter. In the following example we keep only columns where there are at least the 80% of not null values.

In [ ]:
df.dropna(thresh=0.8*len(df),axis=1,inplace=True)

In [ ]:
df.dtypes

age                  int64
sex                 object
steroid             object
antivirals            bool
fatigue             object
malaise             object
anorexia            object
liver_big           object
liver_firm          object
spleen_palpable     object
spiders             object
ascites             object
varices             object
bilirubin          float64
alk_phosphate      float64
sgot               float64
albumin            float64
histology             bool
class               object
dtype: object

In [ ]:
import numpy as np
numeric = df.select_dtypes(include=np.number)
numeric_columns = numeric.columns

In [ ]:
df[numeric_columns] = df[numeric_columns].fillna(df.mean())

<ipython-input-14-fdaac0744f5f>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[numeric_columns] = df[numeric_columns].fillna(df.mean())

In [ ]:
df.isna().sum()/len(df)*100

age                0.000000
sex                0.000000
steroid            0.689655
antivirals         0.000000
fatigue            0.000000
malaise            0.000000
anorexia           0.000000
liver_big          0.000000
liver_firm         0.689655
spleen_palpable    0.689655
spiders            0.689655
ascites            0.689655
varices            0.689655
bilirubin          0.000000
alk_phosphate      0.000000
sgot               0.000000
albumin            0.000000
histology          0.000000
class              0.000000
dtype: float64

In [ ]:
boolean_columns = df.select_dtypes(include=np.object).columns.tolist()
boolean_columns.remove('class')
df[boolean_columns] = df[boolean_columns].astype('bool')

<ipython-input-16-f600210b030b>:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  boolean_columns = df.select_dtypes(include=np.object).columns.tolist()

In [ ]:
df[boolean_columns].fillna(df.mode())

,sex,steroid,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices
0,True,False,False,False,False,False,False,False,False,False,False
1,True,False,True,False,False,False,False,False,False,False,False
2,True,True,True,False,False,True,False,False,False,False,False
3,True,True,False,False,False,True,False,False,False,False,False
4,True,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
150,True,True,True,True,True,True,False,False,True,True,True
151,True,True,True,False,False,True,True,False,False,False,False
152,True,False,True,True,False,False,True,False,True,False,False
153,True,False,True,False,False,True,False,True,True,False,True
154,True,True,True,False,False,True,False,True,True,True,False

In [ ]:
df.isna().sum()/len(df)*100

age                0.0
sex                0.0
steroid            0.0
antivirals         0.0
fatigue            0.0
malaise            0.0
anorexia           0.0
liver_big          0.0
liver_firm         0.0
spleen_palpable    0.0
spiders            0.0
ascites            0.0
varices            0.0
bilirubin          0.0
alk_phosphate      0.0
sgot               0.0
albumin            0.0
histology          0.0
class              0.0
dtype: float64

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/drshahizan/dataset/main/eda/hepatitis.csv')
df.isna().sum()/len(df)*100

age                 0.000000
sex                 0.000000
steroid             0.645161
antivirals          0.000000
fatigue             0.645161
malaise             0.645161
anorexia            0.645161
liver_big           6.451613
liver_firm          7.096774
spleen_palpable     3.225806
spiders             3.225806
ascites             3.225806
varices             3.225806
bilirubin           3.870968
alk_phosphate      18.709677
sgot                2.580645
albumin            10.322581
protime            43.225806
histology           0.000000
class               0.000000
dtype: float64

In [ ]:
numeric = df.select_dtypes(include=np.number)
numeric_columns = numeric.columns

In [ ]:
df.head(10)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.0,42.0,3.5,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.0,32.0,4.0,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.7,46.0,52.0,4.0,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,200.0,4.0,NaN,False,live
5,34,female,True,False,False,False,False,True,False,False,False,False,False,0.9,95.0,28.0,4.0,75.0,False,live
6,51,female,False,False,True,False,True,True,False,True,True,False,False,NaN,NaN,NaN,NaN,NaN,False,die
7,23,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,NaN,NaN,NaN,False,live
8,39,female,True,False,True,False,False,True,True,False,False,False,False,0.7,NaN,48.0,4.4,NaN,False,live
9,30,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,120.0,3.9,NaN,False,live

In [ ]:
df[numeric_columns] = df[numeric_columns].interpolate(method ='linear', limit_direction ='forward')

In [ ]:
df.head(10)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.00,85.0,18.000000,4.000000,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.90,135.0,42.000000,3.500000,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.70,96.0,32.000000,4.000000,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.70,46.0,52.000000,4.000000,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.00,70.5,200.000000,4.000000,77.5,False,live
5,34,female,True,False,False,False,False,True,False,False,False,False,False,0.90,95.0,28.000000,4.000000,75.0,False,live
6,51,female,False,False,True,False,True,True,False,True,True,False,False,0.95,91.6,34.666667,4.133333,77.0,False,die
7,23,female,True,False,False,False,False,True,False,False,False,False,False,1.00,88.2,41.333333,4.266667,79.0,False,live
8,39,female,True,False,True,False,False,True,True,False,False,False,False,0.70,84.8,48.000000,4.400000,81.0,False,live
9,30,female,True,False,False,False,False,True,False,False,False,False,False,1.00,81.4,120.000000,3.900000,83.0,False,live