<a href="https://colab.research.google.com/github/drshahizan/python-tutorial/blob/main/exercise/mohd-nor/lab1b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 1b - Understanding Your Data

Please use the [**Occupation**](https://raw.githubusercontent.com/drshahizan/dataset/main/pandas/u.user) dataset for this exercise.

### Step 1. Import the necessary libraries

In [27]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/drshahizan/dataset/main/pandas/u.user',sep="|")
df.head(10)

   user_id  age gender     occupation zip_code
0        1   24      M     technician    85711
1        2   53      F          other    94043
2        3   23      M         writer    32067
3        4   24      M     technician    43537
4        5   33      F          other    15213
5        6   42      M      executive    98101
6        7   57      M  administrator    91344
7        8   36      M  administrator    05201
8        9   29      M        student    01002
9       10   53      M         lawyer    90703

### Step 2. Import the dataset from [**Occupation**](https://raw.githubusercontent.com/drshahizan/dataset/main/pandas/u.user).

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [28]:
users = df.set_index("user_id",inplace = True)

### Step 4. See the first 25 entries

In [21]:
df.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

### Step 6. What is the number of observations in the dataset?

### Step 7. What is the number of columns in the dataset?

### Step 8. Print the name of all the columns.

### Step 9. How is the dataset indexed?

### Step 10. What is the data type of each column?

### Step 11. Print only the occupation column

### Step 12. How many different occupations are in this dataset?

### Step 13. What is the most frequent occupation?

### Step 14. Summarize the DataFrame.

### Step 15. Summarize all the columns

### Step 16. Summarize only the occupation column

### Step 17. What is the mean age of users?

### Step 18. What is the age with least occurrence?